/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cloud/model2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.19, 0.074, -0.073]} scale={0.012}>
        <mesh geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1.geometry} material={materials.lambert10SG} />
        <mesh geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1_1.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1_2.geometry} material={materials.lambert9SG} />
        <mesh geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1_3.geometry} material={materials.lambert8SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/model2.glb')
