/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";

export function Cloud({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/cloud/model2.glb");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[2, 2, 2]} scale={0.005}>
        <mesh
          geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1.geometry}
          // material={materials.lambert10SG}
        >
          <meshStandardMaterial
            ref={materialRef}
            onBeforeCompile={fadeOnBeforeCompile}
            envMapIntensity={2}
            transparent
          />
        </mesh>
        <mesh
          geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1_1.geometry}
          // material={materials.lambert6SG}
        >
          <meshStandardMaterial
            ref={materialRef}
            onBeforeCompile={fadeOnBeforeCompile}
            envMapIntensity={2}
            transparent
          />
        </mesh>
        <mesh
          geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1_2.geometry}
          // material={materials.lambert9SG}
        >
          <meshStandardMaterial
            ref={materialRef}
            onBeforeCompile={fadeOnBeforeCompile}
            envMapIntensity={2}
            transparent
          />
        </mesh>
        <mesh
          geometry={nodes.Lo_poly_Planet_02_by_Liz_Reddington_RING_1_3.geometry}
          // material={materials.lambert8SG}
        >
          <meshStandardMaterial
            ref={materialRef}
            onBeforeCompile={fadeOnBeforeCompile}
            envMapIntensity={2}
            transparent
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("./models/cloud/model2.glb");
