/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/airplane/model1.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Paperplane(opacity, ...props) {
  const { nodes, materials } = useGLTF("./models/airplane/model1.glb");
  return (
    <group {...props} dispose={null} scale={6}>
      <mesh
        geometry={nodes.mesh1111588455.geometry}
        material={nodes.mesh1111588455.material}
        // position={[0, 2, 4.2]}
        rotation={[0, 1.7, 0.25]}
      />
    </group>
  );
}

useGLTF.preload("./models/airplane/model1.glb");
